<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Protos\vectordb.proto" />
    <None Remove="Views\Chat\Chat.css" />
    <None Remove="Views\Chat\Chat.js" />
    <None Remove="Views\Shared\_Layout.cshtml.css" />
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="Fizzler.Systems.HtmlAgilityPack" Version="1.2.1" />
		<PackageReference Include="Google.Apis.Auth" Version="1.72.0" />
		<PackageReference Include="Grpc.AspNetCore" Version="2.71.0" />
		<PackageReference Include="Grpc.Tools" Version="2.72.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="HtmlAgilityPack" Version="1.11.71" />
		<PackageReference Include="Markdig" Version="0.43.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.36" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="6.0.36">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="System.Numerics.Tensors" Version="9.0.9" />
	</ItemGroup>

  <ItemGroup>
    <Protobuf Include="Protos\vectordb.proto" GrpcServices="Server" />
  </ItemGroup>

</Project>
