// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/vectordb.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace VectorRagDemo.Services {
  public static partial class VectorDbService
  {
    static readonly string __ServiceName = "vectordb.VectorDbService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::VectorRagDemo.Services.SearchRequest> __Marshaller_vectordb_SearchRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::VectorRagDemo.Services.SearchRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::VectorRagDemo.Services.SearchResponse> __Marshaller_vectordb_SearchResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::VectorRagDemo.Services.SearchResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::VectorRagDemo.Services.AddChunkRequest> __Marshaller_vectordb_AddChunkRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::VectorRagDemo.Services.AddChunkRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::VectorRagDemo.Services.AddChunkResponse> __Marshaller_vectordb_AddChunkResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::VectorRagDemo.Services.AddChunkResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::VectorRagDemo.Services.AddBronRequest> __Marshaller_vectordb_AddBronRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::VectorRagDemo.Services.AddBronRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::VectorRagDemo.Services.AddBronResponse> __Marshaller_vectordb_AddBronResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::VectorRagDemo.Services.AddBronResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::VectorRagDemo.Services.AddProjectRequest> __Marshaller_vectordb_AddProjectRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::VectorRagDemo.Services.AddProjectRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::VectorRagDemo.Services.AddProjectResponse> __Marshaller_vectordb_AddProjectResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::VectorRagDemo.Services.AddProjectResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::VectorRagDemo.Services.GetChunkRequest> __Marshaller_vectordb_GetChunkRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::VectorRagDemo.Services.GetChunkRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::VectorRagDemo.Services.ChunkResponse> __Marshaller_vectordb_ChunkResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::VectorRagDemo.Services.ChunkResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::VectorRagDemo.Services.GetScrapingElementsRequest> __Marshaller_vectordb_GetScrapingElementsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::VectorRagDemo.Services.GetScrapingElementsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::VectorRagDemo.Services.GetScrapingElementsResponse> __Marshaller_vectordb_GetScrapingElementsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::VectorRagDemo.Services.GetScrapingElementsResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::VectorRagDemo.Services.GetProjectForUserRequest> __Marshaller_vectordb_GetProjectForUserRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::VectorRagDemo.Services.GetProjectForUserRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::VectorRagDemo.Services.GetProjectForUserResponse> __Marshaller_vectordb_GetProjectForUserResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::VectorRagDemo.Services.GetProjectForUserResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::VectorRagDemo.Services.SearchRequest, global::VectorRagDemo.Services.SearchResponse> __Method_SearchSimilarChunks = new grpc::Method<global::VectorRagDemo.Services.SearchRequest, global::VectorRagDemo.Services.SearchResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SearchSimilarChunks",
        __Marshaller_vectordb_SearchRequest,
        __Marshaller_vectordb_SearchResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::VectorRagDemo.Services.AddChunkRequest, global::VectorRagDemo.Services.AddChunkResponse> __Method_AddChunk = new grpc::Method<global::VectorRagDemo.Services.AddChunkRequest, global::VectorRagDemo.Services.AddChunkResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "AddChunk",
        __Marshaller_vectordb_AddChunkRequest,
        __Marshaller_vectordb_AddChunkResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::VectorRagDemo.Services.AddBronRequest, global::VectorRagDemo.Services.AddBronResponse> __Method_AddBron = new grpc::Method<global::VectorRagDemo.Services.AddBronRequest, global::VectorRagDemo.Services.AddBronResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "AddBron",
        __Marshaller_vectordb_AddBronRequest,
        __Marshaller_vectordb_AddBronResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::VectorRagDemo.Services.AddProjectRequest, global::VectorRagDemo.Services.AddProjectResponse> __Method_AddProject = new grpc::Method<global::VectorRagDemo.Services.AddProjectRequest, global::VectorRagDemo.Services.AddProjectResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "AddProject",
        __Marshaller_vectordb_AddProjectRequest,
        __Marshaller_vectordb_AddProjectResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::VectorRagDemo.Services.GetChunkRequest, global::VectorRagDemo.Services.ChunkResponse> __Method_GetChunkById = new grpc::Method<global::VectorRagDemo.Services.GetChunkRequest, global::VectorRagDemo.Services.ChunkResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetChunkById",
        __Marshaller_vectordb_GetChunkRequest,
        __Marshaller_vectordb_ChunkResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::VectorRagDemo.Services.GetScrapingElementsRequest, global::VectorRagDemo.Services.GetScrapingElementsResponse> __Method_GetScrapingElementsByProject = new grpc::Method<global::VectorRagDemo.Services.GetScrapingElementsRequest, global::VectorRagDemo.Services.GetScrapingElementsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetScrapingElementsByProject",
        __Marshaller_vectordb_GetScrapingElementsRequest,
        __Marshaller_vectordb_GetScrapingElementsResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::VectorRagDemo.Services.GetProjectForUserRequest, global::VectorRagDemo.Services.GetProjectForUserResponse> __Method_GetProjectForUser = new grpc::Method<global::VectorRagDemo.Services.GetProjectForUserRequest, global::VectorRagDemo.Services.GetProjectForUserResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetProjectForUser",
        __Marshaller_vectordb_GetProjectForUserRequest,
        __Marshaller_vectordb_GetProjectForUserResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::VectorRagDemo.Services.VectordbReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of VectorDbService</summary>
    [grpc::BindServiceMethod(typeof(VectorDbService), "BindService")]
    public abstract partial class VectorDbServiceBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::VectorRagDemo.Services.SearchResponse> SearchSimilarChunks(global::VectorRagDemo.Services.SearchRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::VectorRagDemo.Services.AddChunkResponse> AddChunk(global::VectorRagDemo.Services.AddChunkRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::VectorRagDemo.Services.AddBronResponse> AddBron(global::VectorRagDemo.Services.AddBronRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::VectorRagDemo.Services.AddProjectResponse> AddProject(global::VectorRagDemo.Services.AddProjectRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::VectorRagDemo.Services.ChunkResponse> GetChunkById(global::VectorRagDemo.Services.GetChunkRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::VectorRagDemo.Services.GetScrapingElementsResponse> GetScrapingElementsByProject(global::VectorRagDemo.Services.GetScrapingElementsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::VectorRagDemo.Services.GetProjectForUserResponse> GetProjectForUser(global::VectorRagDemo.Services.GetProjectForUserRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(VectorDbServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_SearchSimilarChunks, serviceImpl.SearchSimilarChunks)
          .AddMethod(__Method_AddChunk, serviceImpl.AddChunk)
          .AddMethod(__Method_AddBron, serviceImpl.AddBron)
          .AddMethod(__Method_AddProject, serviceImpl.AddProject)
          .AddMethod(__Method_GetChunkById, serviceImpl.GetChunkById)
          .AddMethod(__Method_GetScrapingElementsByProject, serviceImpl.GetScrapingElementsByProject)
          .AddMethod(__Method_GetProjectForUser, serviceImpl.GetProjectForUser).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, VectorDbServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_SearchSimilarChunks, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::VectorRagDemo.Services.SearchRequest, global::VectorRagDemo.Services.SearchResponse>(serviceImpl.SearchSimilarChunks));
      serviceBinder.AddMethod(__Method_AddChunk, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::VectorRagDemo.Services.AddChunkRequest, global::VectorRagDemo.Services.AddChunkResponse>(serviceImpl.AddChunk));
      serviceBinder.AddMethod(__Method_AddBron, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::VectorRagDemo.Services.AddBronRequest, global::VectorRagDemo.Services.AddBronResponse>(serviceImpl.AddBron));
      serviceBinder.AddMethod(__Method_AddProject, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::VectorRagDemo.Services.AddProjectRequest, global::VectorRagDemo.Services.AddProjectResponse>(serviceImpl.AddProject));
      serviceBinder.AddMethod(__Method_GetChunkById, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::VectorRagDemo.Services.GetChunkRequest, global::VectorRagDemo.Services.ChunkResponse>(serviceImpl.GetChunkById));
      serviceBinder.AddMethod(__Method_GetScrapingElementsByProject, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::VectorRagDemo.Services.GetScrapingElementsRequest, global::VectorRagDemo.Services.GetScrapingElementsResponse>(serviceImpl.GetScrapingElementsByProject));
      serviceBinder.AddMethod(__Method_GetProjectForUser, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::VectorRagDemo.Services.GetProjectForUserRequest, global::VectorRagDemo.Services.GetProjectForUserResponse>(serviceImpl.GetProjectForUser));
    }

  }
}
#endregion
